# Test workflow
on:
  pull_request:
    branches:
      - main
      - feature-workflow

jobs:
  cypress_tests:
    runs-on: [self-hosted, macOS, X64]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Start MongoDB
        run: |
          cd server/
          node init.js
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: |
          cd server/
          npm install
      - name: Start client and server
        run: |
          cd ..
          cd client/
          npm start &
          cd ..
          cd server/
          node server.js
      - name: Run Cypress tests in headless mode
        run: |
          cd ..
          cd client/
          npx cypress run
    

  jest_tests:
    runs-on: [self-hosted, macOS, X64]
    steps: 
      - name: Checkout Repo 
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Install dependencies
        run:  |
          cd server/
          npm install
      - name: Run Jest tests
        run: |
          cd server/
          npm test
      
