# Test workflow
on:
  pull_request:
    branches:
      - main

jobs:
  cypress_tests:
    runs-on: [self-hosted, macOS, X64]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '16.15'
      - run: npm install --prefix client
      - run: npm install --prefix server
      - name: Start MongoDB
        run: |
          cd server/
          node init.js
      - name: Install Cypress
        run: npm install cypress --save-dev
      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          project: ./client
          start: npm run start --prefix client, npm run start --prefix server
          wait-on: 'http://localhost:3000,http://localhost:8000'
          browser: chrome
          timeout: 400

  jest_tests:
    runs-on: [self-hosted, macOS, X64]
    steps: 
      - name: Checkout Repo 
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Install dependencies
        run:  |
          cd server/
          npm install
      - name: Run Jest tests
        run: |
          cd server/
          npm test
      
